# Generated by Django 4.2.6 on 2023-10-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='winbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSM', models.CharField(max_length=100)),
                ('Client_Joignable', models.BooleanField(default=False)),
                ('Raison_de_non_commande', models.TextField(blank=True, null=True)),
                ('Feedback_post_Voucher', models.TextField(blank=True, null=True)),
                ('Mail_client_Valide', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('Treated_By', models.CharField(max_length=100)),
                ('Submission_DateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'winback_table',
            },
        ),
    ]
