# Generated by Django 4.2.6 on 2023-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_winbacktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winbacktable',
            name='Client_Joignable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
