# Generated by Django 4.2.6 on 2023-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_winbacktable_client_joignable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winbacktable',
            name='Mail_client_Valide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='winbacktable',
            name='Submission_DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winbacktable',
            name='Treated_By',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
