# Generated by Django 4.2.6 on 2023-10-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_winbacktable_mail_client_valide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winbacktable',
            name='Client_Joignable',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='winbacktable',
            name='Mail_client_Valide',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
