# Generated by Django 4.2.6 on 2023-10-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_winbacktable_client_joignable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winbacktable',
            old_name='Mail_client_Valide',
            new_name='Email',
        ),
    ]
