# Generated by Django 4.2.6 on 2023-10-30 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_winback2_winback2results'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('GSM', models.IntegerField(blank=True, null=True)),
                ('Client_Joignable', models.TextField(blank=True, null=True)),
                ('Raison_de_non_commande', models.TextField(blank=True, null=True)),
                ('Feedback_post_Voucher', models.TextField(blank=True, null=True)),
                ('Mail_client_Valide', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(blank=True, null=True)),
                ('treated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='winbackTable',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='Feedback_post_Voucher',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='Mail_client_Valide',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='Raison_de_non_commande',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='winback2results',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
