# Generated by Django 4.2.6 on 2023-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_campagneresults_delete_winbacktable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_case', models.IntegerField(choices=[(1, 'Case 1'), (2, 'Case 2'), (3, 'Case 3')])),
            ],
        ),
    ]
