# Generated by Django 4.2.6 on 2023-10-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_choicemodel_delete_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemodel',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='selected_choices',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
