# Generated by Django 4.2.6 on 2023-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_choicemodel_selected_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ningen_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True,  serialize=False, verbose_name='ID')),
                ('Ngroupe', models.IntegerField(blank=True, null=True)),
                ('Matricule', models.IntegerField(blank=True, null=True)),
                ('ID_Beside', models.CharField(blank=True, max_length=30, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('Nom', models.CharField(blank=True, max_length=20, null=True)),
                ('CL', models.CharField(choices=[('', ''), ('Khaoula Werghi', 'Khaoula Werghi'), ('Anis Hedhli', 'Anis Hedhli'), ('Ishrak Ben Rjab', 'Ishrak Ben Rjab'), ('Molka CHOUIKA', 'Molka CHOUIKA'), ('Mohamed Amine ZOUAOUI', 'Mohamed Amine ZOUAOUI')], max_length=50)),
                ('N1', models.CharField(choices=[('Mehrzia Hannafi', 'Mehrzia Hannafi'), ('Mehdi Zyoudi', 'Mehdi Zyoudi'), ('Ines Dridi', 'Ines Dridi')], max_length=25)),
                ('N2', models.CharField(choices=[('Mounir Bech', 'Mounir Bech'), ('Ali Hamouda', 'Ali Hamouda')], max_length=25)),
                ('Date_embauche', models.DateField(blank=True, null=True)),
                ('Date_fin_1ere_péride_d_essai', models.DateField(blank=True, null=True)),
                ('Type_de_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CIVP', 'CIVP')], max_length=10)),
                ('Régime_horaire', models.CharField(choices=[('20', '20'), ('24', '24'), ('28', '28'), ('30', '30'), ('40', '40'), ('45', '45'), ('48', '48')], max_length=2)),
                ('CIN', models.PositiveIntegerField()),
                ('Titulaire', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3)),
                ('Date_de_titularisation', models.DateField(blank=True, null=True)),
                ('Tel', models.IntegerField()),
                ('Date_de_naissance', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('Situation', models.CharField(choices=[('marié', 'marié'), ('célibataire', 'célibataire')], max_length=20)),
                ('Nombre_d_enfants', models.IntegerField(blank=True, null=True)),
                ('Niveau_d_etude', models.CharField(choices=[('Lycée/Bac non validé', 'Lycée/Bac non validé'), ('bac', 'bac'), ('bac+1', 'bac+1'), ('bac+2', 'bac+2'), ('bac+3', 'bac+3'), ('bac+4', 'bac+4'), ('bac+5', 'bac+5'), ('BTP', 'BTP')], max_length=20)),
                ('Diplome', models.CharField(blank=True, max_length=255, null=True)),
                ('Centre_d_intérêt', models.CharField(blank=True, max_length=255, null=True)),
                ('Mail_personel', models.EmailField(blank=True, max_length=254, null=True)),
                ('Adresse_postale', models.CharField(blank=True, max_length=255, null=True)),
                ('Statut_à_date', models.BooleanField(default=True)),
                ('Mission_spéciale', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_FPE', models.DateField(blank=True, null=True)),
                ('Commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChoiceModel',
        ),
    ]
