# Generated by Django 4.2.6 on 2023-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ningen_staff_delete_choicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', ''), ('Khaoula Werghi', 'Khaoula Werghi'), ('Anis Hedhli', 'Anis Hedhli'), ('Ishrak Ben Rjab', 'Ishrak Ben Rjab'), ('Molka CHOUIKA', 'Molka CHOUIKA'), ('Mohamed Amine ZOUAOUI', 'Mohamed Amine ZOUAOUI')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ningen_staff',
            name='CL',
        ),
        migrations.AddField(
            model_name='ningen_staff',
            name='CL',
            field=models.ManyToManyField(to='myapp.clchoicemodel'),
        ),
    ]
