# Generated by Django 4.2.6 on 2023-11-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_clchoicemodel_remove_ningen_staff_cl_ningen_staff_cl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clchoicemodel',
            old_name='name',
            new_name='CL',
        ),
    ]
