# Generated by Django 4.2.6 on 2023-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_clchoicemodel_cl_clchoicemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='CIN',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
