# Generated by Django 4.2.6 on 2023-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_ningen_staff_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='Niveau_d_etude',
            field=models.CharField(blank=True, choices=[('Lycée/Bac non validé', 'Lycée/Bac non validé'), ('bac', 'bac'), ('bac+1', 'bac+1'), ('bac+2', 'bac+2'), ('bac+3', 'bac+3'), ('bac+4', 'bac+4'), ('bac+5', 'bac+5'), ('BTP', 'BTP')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ningen_staff',
            name='Situation',
            field=models.CharField(blank=True, choices=[('marié', 'marié'), ('célibataire', 'célibataire')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ningen_staff',
            name='Tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
