# Generated by Django 4.2.6 on 2023-11-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_clchoicemodel_name_alter_ningen_staff_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='Situation',
            field=models.CharField(choices=[('marié', 'marié'), ('célibataire', 'célibataire')], max_length=20, null=True),
        ),
    ]
