# Generated by Django 4.2.6 on 2023-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_ningen_staff_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='ID_Beside',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ningen_staff',
            name='Ngroupe',
            field=models.IntegerField(default=None),
        ),
    ]
