# Generated by Django 4.2.6 on 2023-11-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_ningen_staff_id_beside_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_activite', models.PositiveIntegerField()),
                ('nom_activite', models.CharField(choices=[('Jumia TN', 'Jumia TN'), ('Jumia DZ', 'Jumia DZ'), ('kool', 'kool'), ('Arkan', 'Arkan')], max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ningen_staff')),
            ],
            options={
                'unique_together': {('agent', 'numero_activite')},
            },
        ),
    ]
