# Generated by Django 4.2.6 on 2023-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='CANAL_IB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='CANAL_Live_Chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='CANAL_OB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='LOB_BO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='LOB_CS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='LOB_Confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='LOB_Sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='Line_of_business',
            field=models.CharField(choices=[('CS', 'CS'), ('ODS', 'ODS'), ('PG', 'PG')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
