# Generated by Django 4.2.6 on 2023-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_activite_canal_ib_activite_canal_live_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='Line_of_business',
            field=models.CharField(choices=[('CS', 'CS'), ('Confirmation', 'Confirmation'), ('ODS', 'ODS'), ('PG', 'PG')], max_length=50),
        ),
    ]
