# Generated by Django 4.2.6 on 2023-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_activite_line_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='ningen_staff',
            name='Activité_actuelle',
            field=models.CharField(blank=True, choices=[('Jumia TN', 'Jumia TN'), ('Jumia DZ', 'Jumia DZ'), ('Kool', 'Kool'), ('Arkan', 'Arkan')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ningen_staff',
            name='Affectation_actuelle_CANAL',
            field=models.CharField(blank=True, choices=[('IB', 'IB'), ('IB/OB', 'IB/OB'), ('LiveChat', 'LiveChat'), ('Voice', 'Voice')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ningen_staff',
            name='LOB_actuelle',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('Confirmation', 'Confirmation'), ('ODS', 'ODS'), ('PG', 'PG')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ningen_staff',
            name='Micro_activité_actuelle',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('Confirmation', 'Confirmation'), ('ODS', 'ODS'), ('PG', 'PG')], max_length=50, null=True),
        ),
    ]
