# Generated by Django 4.2.6 on 2023-11-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_ningen_staff_activité_actuelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='LOB_actuelle',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('BO', 'BO'), ('Confirmation', 'Confirmation'), ('ODS', 'ODS'), ('PG', 'PG')], max_length=50, null=True),
        ),
    ]
