# Generated by Django 4.2.6 on 2023-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_ningen_staff_cin_alter_ningen_staff_n1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='CIN',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
