# Generated by Django 4.2.6 on 2023-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_ningen_staff_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='CL',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.clchoicemodel'),
        ),
    ]
