# Generated by Django 4.2.6 on 2023-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_ningen_staff_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ningen_staff',
            name='TT',
            field=models.BooleanField(default=False),
        ),
    ]
