# Generated by Django 4.2.6 on 2023-11-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_ningen_staff_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ningen_staff',
            name='Commentaire',
        ),
    ]
