# Generated by Django 4.2.6 on 2023-11-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_ningen_staff_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ningen_staff',
            name='Fonction',
            field=models.CharField(blank=True, choices=[('Chargé Client', 'Chargé Client'), ('Conseiller Leader', 'Conseiller Leader')], max_length=50, null=True),
        ),
    ]
