# Generated by Django 4.2.6 on 2023-11-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_ningen_staff_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ningen_staff',
            name='Genre',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=2, null=True),
        ),
    ]
