# Generated by Django 4.2.6 on 2023-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_ningen_staff_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ningen_staff',
            name='Statut_à_date',
            field=models.CharField(blank=True, choices=[('Actif', 'Actif'), ('démission', 'démission'), ('FPE', 'FPE')], max_length=50, null=True),
        ),
    ]
