# Generated by Django 4.2.6 on 2023-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_ningen_staff_statut_à_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='nom_activite',
            field=models.CharField(choices=[('Jumia TN', 'Jumia TN'), ('Jumia DZ', 'Jumia DZ'), ('KooL', 'KooL'), ('Arkan', 'Arkan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ningen_staff',
            name='Activité_actuelle',
            field=models.CharField(blank=True, choices=[('Jumia TN', 'Jumia TN'), ('Jumia DZ', 'Jumia DZ'), ('KooL', 'KooL'), ('Arkan', 'Arkan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ningen_staff',
            name='LOB_actuelle',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('BO', 'BO'), ('Confirmation', 'Confirmation'), ('ODS', 'ODS'), ('Sales', 'Sales')], max_length=50, null=True),
        ),
    ]
