# Generated by Django 4.2.6 on 2023-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_activite_nom_activite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ningen_staff',
            old_name='Date_fin_1ere_péride_d_essai',
            new_name='Date_fin_1ere_période_d_essai',
        ),
        migrations.AlterField(
            model_name='ningen_staff',
            name='N1',
            field=models.CharField(choices=[('Mehrzia Hannafi', 'Mehrzia Hannafi'), ('Ines Dridi', 'Ines Dridi'), ('Mounir Bech', 'Mounir Bech')], max_length=25),
        ),
    ]
