# Generated by Django 4.2.6 on 2023-11-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_date_fin_1ere_péride_d_essai_ningen_staff_date_fin_1ere_période_d_essai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='LOB_BO',
            new_name='Skills_BO',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='LOB_CS',
            new_name='Skills_CS',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='LOB_Confirmation',
            new_name='Skills_Confirmation',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='LOB_Sales',
            new_name='Skills_Sales',
        ),
    ]
