# Generated by Django 4.2.6 on 2023-11-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_ningen_staff_type_de_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='activiteChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Jumia TN', 'Jumia TN'), ('Jumia DZ', 'Jumia DZ'), ('KooL', 'KooL'), ('Arkan', 'Arkan')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ningen_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.IntegerField(blank=True, null=True)),
                ('ID_Beside', models.CharField(default=None, max_length=30)),
                ('Prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('Nom', models.CharField(blank=True, max_length=20, null=True)),
                ('Genre', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=2, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('Situation', models.CharField(choices=[('marié', 'marié'), ('célibataire', 'célibataire')], max_length=20, null=True)),
                ('Nombre_d_enfants', models.IntegerField(blank=True, null=True)),
                ('Niveau_d_etude', models.CharField(blank=True, choices=[('Lycée/Bac non validé', 'Lycée/Bac non validé'), ('bac', 'bac'), ('bac+1', 'bac+1'), ('bac+2', 'bac+2'), ('bac+3', 'bac+3'), ('bac+4', 'bac+4'), ('bac+5', 'bac+5'), ('bac+6', 'bac+6'), ('BTP', 'BTP')], max_length=20, null=True)),
                ('Diplome', models.CharField(blank=True, max_length=255, null=True)),
                ('Centre_d_intérêt', models.CharField(blank=True, max_length=255, null=True)),
                ('Mail_personel', models.EmailField(blank=True, max_length=254, null=True)),
                ('Tel1', models.IntegerField(blank=True, null=True)),
                ('Tel2', models.IntegerField(blank=True, null=True)),
                ('Adresse_postale', models.CharField(blank=True, max_length=255, null=True)),
                ('Fonction', models.CharField(blank=True, choices=[('Floor manager quality and process', 'Floor manager quality and process'), ('Responsable WFM', 'Responsable WFM'), ('Responsable IT', 'Responsable IT'), ('Dir PROD', 'Dir PROD'), ('MANGING ASSOCIATE', 'MANGING ASSOCIATE'), ('DPH', 'DPH'), ('Responsable Qualité', 'Responsable Qualité'), ('Floor Manager ', 'Floor Manager '), ('Team leader', 'Team leader'), ('Data Analyst junior', 'Data Analyst junior'), ('Assistante de direction', 'Assistante de direction'), ('Développeur Junior', 'Développeur Junior'), ('Floor Manager ', 'Floor Manager ')], max_length=50, null=True)),
                ('N1', models.CharField(choices=[('Mounir Bech', 'Mounir Bech'), ("Samiha M'RABET", "Samiha M'RABET"), ('Stéphane DUCREUX', 'Stéphane DUCREUX'), ('Ali HAMOUDA', 'Ali HAMOUDA'), ('Manel MADOURI', 'Manel MADOURI'), ('Aymen DRIDI', 'Aymen DRIDI')], max_length=25)),
                ('Date_embauche', models.DateField(blank=True, null=True)),
                ('Durrée_mission', models.DurationField(blank=True, null=True)),
                ('Date_fin_1ere_période_d_essai', models.DateField(blank=True, null=True)),
                ('Type_de_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CIVP', 'CIVP'), ('EL Karama', 'EL Karama'), ('Stage', 'Stage')], max_length=10)),
                ('Régime_horaire', models.CharField(choices=[('20', '20'), ('24', '24'), ('28', '28'), ('30', '30'), ('40', '40'), ('45', '45'), ('48', '48')], max_length=2)),
                ('CIN', models.CharField(blank=True, max_length=8, null=True)),
                ('Titulaire', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3)),
                ('Date_de_titularisation', models.DateField(blank=True, null=True)),
                ('Statut_à_date', models.CharField(blank=True, choices=[('Actif', 'Actif'), ('démission', 'démission'), ('FPE', 'FPE')], max_length=50, null=True)),
                ('Date_FPE', models.DateField(blank=True, null=True)),
                ('Activite', models.ManyToManyField(blank=True, to='myapp.activitechoicemodel')),
            ],
        ),
    ]
