# Generated by Django 4.2.6 on 2023-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_activitechoicemodel_ningen_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='ningen_management',
            name='Date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
