# Generated by Django 4.2.6 on 2023-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_ningen_management_activite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ningen_management',
            name='Activite',
        ),
        migrations.AddField(
            model_name='ningen_management',
            name='Activite',
            field=models.ManyToManyField(blank=True, to='myapp.activitechoicemodel'),
        ),
    ]
