# Generated by Django 4.2.6 on 2023-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_ningen_management_activite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='activiteChoiceModel',
            new_name='actChoiceModel',
        ),
        migrations.RenameField(
            model_name='ningen_management',
            old_name='Activite',
            new_name='Act',
        ),
    ]
