# Generated by Django 4.2.6 on 2023-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_rename_activitechoicemodel_actchoicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ningen_management',
            name='Act',
        ),
        migrations.AddField(
            model_name='ningen_management',
            name='Act',
            field=models.CharField(blank=True, choices=[('Jumia TN', 'Jumia TN'), ('Jumia DZ', 'Jumia DZ'), ('KooL', 'KooL'), ('Arkan', 'Arkan')], max_length=50, null=True),
        ),
    ]
