# Generated by Django 4.2.6 on 2023-11-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_ningen_management_act_ningen_management_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ningen_management',
            name='Act',
        ),
        migrations.AddField(
            model_name='ningen_management',
            name='Act',
            field=models.ManyToManyField(blank=True, to='myapp.actchoicemodel'),
        ),
    ]
