# Generated by Django 4.2.7 on 2023-11-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_ningen_management_act_ningen_management_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_day', models.IntegerField(default=0)),
                ('id_upload', models.IntegerField(default=0)),
                ('full_name', models.CharField(max_length=255)),
                ('traitement', models.CharField(max_length=255)),
                ('hour', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('full_name', 'hour', 'date')},
            },
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_upload', models.IntegerField(default=0)),
                ('nom_excel', models.CharField(max_length=255)),
                ('workhour_dispo', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('id_upload',)},
            },
        ),
    ]
